## Default-Settings für den Game-Client

[general]
locale = "en"

[graphics]
resolution = "1920x1080"
ui_scale = 1.0
fullscreen = false
render_distance = "Far"
field_of_view = 90

[audio]
master_volume = 0.8
music_volume = 0.5
sfx_volume = 0.7
voice_volume = 0.9

