[general]
locale = "en"

[graphics]
resolution = "1920x1080"
ui_scale = 1.0
fullscreen = false
# accessibility_mode = "None" # Options: "None", "ColorBlind", "HighContrast"
# v_sync = true
# anti_aliasing = "TAA" # Options: "None", "FXAA", "TAA"
# texture_quality = "High" # Options: "Low", "Medium", "High", "Ultra"
# shadow_quality = "High" # Options: "Low", "Medium", "High", "Ultra"
# post_processing = "High" # Options: "Low", "Medium", "High", "Ultra"
# ambient_occlusion = "SSAO" # Options: "None", "SSAO", "HBAO+"
# motion_blur = false
render_distance = "Far" # Options: "Near", "Medium", "Far", "Ultra"
field_of_view = 90      # Range: 60-120

[audio]
master_volume = 0.8 # Range: 0.0-1.0
music_volume = 0.5  # Range: 0.0-1.0
sfx_volume = 0.7    # Range: 0.0-1.0
voice_volume = 0.9  # Range: 0.0-1.0
# surround_sound = true
