## Default-Settings für den Game-Server (autoritative Werte)

[general]
locale = "en"

[wizard]
tick_rate = 20
fps = 60
autostart = false
max_login_tries = 10

# Beispiel: Gameplay-/Shared-Werte würden hier liegen (server-autoritative)
#[gameplay]
#max_players = 16
#allow_mods = false

