[meta]
devices = ["keyboard"]
version = "0.1.0"

[global]
Quit = ["ctrl+c"]
Help = ["ctrl+h"]

[start]
Submit = ["enter"]
# NextField = ["tab", "down"]
# PreviousField = ["shift+tab", "up"]
# ResetFields = ["ctrl+r"]

[logo]
