[package]
name = "util"
version = "0.1.0"
edition.workspace = true


[lib]
path = "src/lib.rs"
# doctest = false # Enable if you want to skip doctests initially.

[features]
server = []
client = []
[dependencies]
rust-embed.workspace = true

[dev-dependencies]
