[package]
name = "paths"
version = "0.1.0"
edition.workspace = true


[lib]
path = "src/paths.rs"

[dependencies]
dirs.workspace = true
regex.workspace = true
globset.workspace = true
anyhow.workspace = true
serde.workspace = true
unicase.workspace = true
