[package]
name = "network_shared"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
quinn = { workspace = true }
tokio = { workspace = true }
bincode = "1"
settings = { workspace = true }
